In [1]:
import pandas as pd
import os
import re

# Folder and directories

Experiment 1 (One obstacle) has 4 runs

Experiment 2 (One obstacle) has 5 runs

Experiment 3 (One obstacle) has 4 runs

In [2]:
EXPERIMENT = 1
RUN = 1

In [3]:
PATH = "/home/tmr/Documents/PhD/My_PhD/code/datasets/thor/tsvs/"

In [4]:
exp_path = os.path.join(PATH, f"Exp_{EXPERIMENT}_run_{RUN}_6D.tsv")

In [5]:
exp_path

'/home/tmr/Documents/PhD/My_PhD/code/datasets/thor/tsvs/Exp_1_run_1_6D.tsv'

# Loading

In [6]:
pd.read_csv(exp_path, sep = "\t", header = 10)

,Frame,Time,L_frame X,Y,Z,Roll,Pitch,Yaw,Residual,Rot[0],...,Rot[0].12,Rot[1].12,Rot[2].12,Rot[3].12,Rot[4].12,Rot[5].12,Rot[6].12,Rot[7].12,Rot[8].12,Unnamed: 222
0,1,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
1,2,0.01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
2,3,0.02,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
3,4,0.03,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
4,5,0.04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33892,33893,338.92,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
33893,33894,338.93,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
33894,33895,338.94,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
33895,33896,338.95,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
33896,33897,338.96,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN

In [7]:
df = pd.read_csv(exp_path, sep = "\t", header = 10).dropna(axis = 1)

In [8]:
col_list = df.columns.tolist()
new_columns = []
prev_column = col_list[0]
for i, column in enumerate(col_list):
    if re.match("Y.*", column) and re.match("Helmet.*",prev_col_name):
        new_columns.append(prev_col_name + " Y")
    else:
        new_columns.append(column)
    prev_col_name = column.split(" ")[0]
df.columns = new_columns

Checking if all data is here:

* 13 rigid bodies
* 16 coordinates
* 2 columns for time and frame

In [9]:
df.shape[1] == 16*13 + 2

True

In [10]:
df.head(20)

,Frame,Time,L_frame X,Y,Z,Roll,Pitch,Yaw,Residual,Rot[0],...,Residual.12,Rot[0].12,Rot[1].12,Rot[2].12,Rot[3].12,Rot[4].12,Rot[5].12,Rot[6].12,Rot[7].12,Rot[8].12
0,1,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2,0.01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3,0.02,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4,0.03,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5,0.04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,6,0.05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,7,0.06,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,8,0.07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,9,0.08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,10,0.09,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,11,0.10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,12,0.11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,13,0.12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,14,0.13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,15,0.14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,16,0.15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,17,0.16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,18,0.17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,19,0.18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,20,0.19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# Roles

In [11]:
if EXPERIMENT == 1:
    if RUN == 1:
        N_GROUPS = 2
        VISITORS_GROUP1 = [6,7,5] 
        VISITORS_GROUP2 = [8,2,4]
    elif RUN == 2:
        N_GROUPS = 2
        VISITORS_GROUP1 = [2,6,7,5] 
        VISITORS_GROUP2 = [8, 4]
    elif RUN == 3:
        N_GROUPS = 3
        VISITORS_GROUP1 = [6,7,8]
        VISITORS_GROUP2 = [4,5]
        VISITORS_GROUP3 = [2]
    elif RUN == 4:
        N_GROUPS = 2
        VISITORS_GROUP1 = [2, 4, 5, 7, 8]
        VISITORS_GROUP2 = [6]
    
    WORKERS_UTILITY = [3]
    WOKERS_LAB = [9]

if EXPERIMENT == 2:
    if RUN == 1:
        N_GROUPS = 2
        VISITORS_GROUP1 = [4,5,6] 
        VISITORS_GROUP2 = [3,7,9]
    elif RUN == 2:
        N_GROUPS = 2
        VISITORS_GROUP1 = [3,5,6,9] 
        VISITORS_GROUP2 = [7, 4]
    elif RUN == 3:
        N_GROUPS = 3
        VISITORS_GROUP1 = [5,7,9]
        VISITORS_GROUP2 = [4,6]
        VISITORS_GROUP3 = [3]
    elif RUN == 4:
        N_GROUPS = 2
        VISITORS_GROUP1 = [3,5,6,7,9]
        VISITORS_GROUP2 = [4]
    elif RUN == 5:
        N_GROUPS = 3
        VISITORS_GROUP1 = [3, 6]
        VISITORS_GROUP2 = [4, 9]
        VISITORS_GROUP3 = [5, 7]
    
    WORKERS_UTILITY = [2]
    WOKERS_LAB = [8]
    
if EXPERIMENT == 3:
    if RUN == 1:
        N_GROUPS = 2
        VISITORS_GROUP1 = [2,3,8] 
        VISITORS_GROUP2 = [6,7,9]
    elif RUN == 2:
        N_GROUPS = 2
        VISITORS_GROUP1 = [2,8,9] 
        VISITORS_GROUP2 = [3,6,7]
    elif RUN == 3:
        N_GROUPS = 3
        VISITORS_GROUP1 = [2,3,7]
        VISITORS_GROUP2 = [8,9]
        VISITORS_GROUP3 = [6]
    elif RUN == 4:
        N_GROUPS = 2
        VISITORS_GROUP1 = [2,3,6,7,9]
        VISITORS_GROUP2 = [8]
    
    WORKERS_UTILITY = [5]
    WOKERS_LAB = [4]
    
INSPECTOR = [10]

# Trajectories from rigid bodies

In [13]:
df.filter(regex=("Helmet.*"))

,Helmet_1 X,Helmet_1 Y,Helmet_2 X,Helmet_2 Y,Helmet_3 X,Helmet_3 Y,Helmet_4 X,Helmet_4 Y,Helmet_5 X,Helmet_5 Y,Helmet_6 X,Helmet_6 Y,Helmet_7 X,Helmet_7 Y,Helmet_8 X,Helmet_8 Y,Helmet_9 X,Helmet_9 Y,Helmet_10 X,Helmet_10 Y
0,0.0,0.0,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2277.40052,-2550.50965,0.00000,0.00000
1,0.0,0.0,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2275.30137,-2551.77190,0.00000,0.00000
2,0.0,0.0,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2275.22965,-2551.74371,0.00000,0.00000
3,0.0,0.0,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2276.18227,-2549.71645,0.00000,0.00000
4,0.0,0.0,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2276.28525,-2549.60864,0.00000,0.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33892,0.0,0.0,0.0,0.0,3939.04719,4026.79999,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2262.03667,-2193.79295,-1152.53986,-1393.96025
33893,0.0,0.0,0.0,0.0,3948.16169,4027.66884,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2260.65806,-2201.29767,-1150.58293,-1393.40658
33894,0.0,0.0,0.0,0.0,3957.39158,4028.57036,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2259.28937,-2208.90899,-1149.15471,-1392.86863
33895,0.0,0.0,0.0,0.0,3966.73467,4029.52073,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2257.96629,-2216.67865,-1147.56945,-1392.36533
33896,0.0,0.0,0.0,0.0,3976.11472,4030.52546,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2256.75970,-2224.61066,-1146.01798,-1391.93779

In [31]:
merged_df = pd.merge(df[["Frame", "Time"]], df.filter(regex=("Helmet.*")), left_index=True, right_index=True)

In [41]:
merged_df

,Frame,Time,Helmet_1 X,Helmet_1 Y,Helmet_2 X,Helmet_2 Y,Helmet_3 X,Helmet_3 Y,Helmet_4 X,Helmet_4 Y,...,Helmet_6 X,Helmet_6 Y,Helmet_7 X,Helmet_7 Y,Helmet_8 X,Helmet_8 Y,Helmet_9 X,Helmet_9 Y,Helmet_10 X,Helmet_10 Y
0,1,0.00,0.0,0.0,0.0,0.0,0.00000,0.00000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2277.40052,-2550.50965,0.00000,0.00000
1,2,0.01,0.0,0.0,0.0,0.0,0.00000,0.00000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2275.30137,-2551.77190,0.00000,0.00000
2,3,0.02,0.0,0.0,0.0,0.0,0.00000,0.00000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2275.22965,-2551.74371,0.00000,0.00000
3,4,0.03,0.0,0.0,0.0,0.0,0.00000,0.00000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2276.18227,-2549.71645,0.00000,0.00000
4,5,0.04,0.0,0.0,0.0,0.0,0.00000,0.00000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2276.28525,-2549.60864,0.00000,0.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33892,33893,338.92,0.0,0.0,0.0,0.0,3939.04719,4026.79999,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2262.03667,-2193.79295,-1152.53986,-1393.96025
33893,33894,338.93,0.0,0.0,0.0,0.0,3948.16169,4027.66884,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2260.65806,-2201.29767,-1150.58293,-1393.40658
33894,33895,338.94,0.0,0.0,0.0,0.0,3957.39158,4028.57036,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2259.28937,-2208.90899,-1149.15471,-1392.86863
33895,33896,338.95,0.0,0.0,0.0,0.0,3966.73467,4029.52073,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2257.96629,-2216.67865,-1147.56945,-1392.36533
33896,33897,338.96,0.0,0.0,0.0,0.0,3976.11472,4030.52546,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2256.75970,-2224.61066,-1146.01798,-1391.93779

# Downsampling

In [43]:
time_df = merged_df.copy()

In [49]:
time_df["date"] = pd.to_datetime(time_df["Time"], unit="s")

In [50]:
time_df

,Frame,Time,Helmet_1 X,Helmet_1 Y,Helmet_2 X,Helmet_2 Y,Helmet_3 X,Helmet_3 Y,Helmet_4 X,Helmet_4 Y,...,Helmet_6 Y,Helmet_7 X,Helmet_7 Y,Helmet_8 X,Helmet_8 Y,Helmet_9 X,Helmet_9 Y,Helmet_10 X,Helmet_10 Y,date
0,1,0.00,0.0,0.0,0.0,0.0,0.00000,0.00000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2277.40052,-2550.50965,0.00000,0.00000,1970-01-01 00:00:00.000
1,2,0.01,0.0,0.0,0.0,0.0,0.00000,0.00000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2275.30137,-2551.77190,0.00000,0.00000,1970-01-01 00:00:00.010
2,3,0.02,0.0,0.0,0.0,0.0,0.00000,0.00000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2275.22965,-2551.74371,0.00000,0.00000,1970-01-01 00:00:00.020
3,4,0.03,0.0,0.0,0.0,0.0,0.00000,0.00000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2276.18227,-2549.71645,0.00000,0.00000,1970-01-01 00:00:00.030
4,5,0.04,0.0,0.0,0.0,0.0,0.00000,0.00000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2276.28525,-2549.60864,0.00000,0.00000,1970-01-01 00:00:00.040
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33892,33893,338.92,0.0,0.0,0.0,0.0,3939.04719,4026.79999,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2262.03667,-2193.79295,-1152.53986,-1393.96025,1970-01-01 00:05:38.920
33893,33894,338.93,0.0,0.0,0.0,0.0,3948.16169,4027.66884,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2260.65806,-2201.29767,-1150.58293,-1393.40658,1970-01-01 00:05:38.930
33894,33895,338.94,0.0,0.0,0.0,0.0,3957.39158,4028.57036,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2259.28937,-2208.90899,-1149.15471,-1392.86863,1970-01-01 00:05:38.940
33895,33896,338.95,0.0,0.0,0.0,0.0,3966.73467,4029.52073,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2257.96629,-2216.67865,-1147.56945,-1392.36533,1970-01-01 00:05:38.950
33896,33897,338.96,0.0,0.0,0.0,0.0,3976.11472,4030.52546,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2256.75970,-2224.61066,-1146.01798,-1391.93779,1970-01-01 00:05:38.960

In [107]:
time_df[["date" ,"Helmet_8 X", "Helmet_8 Y", "Helmet_9 X", "Helmet_9 Y", "Helmet_10 X", "Helmet_10 Y"]].resample("400ms",on = "date").mean().head(60)

,Helmet_8 X,Helmet_8 Y,Helmet_9 X,Helmet_9 Y,Helmet_10 X,Helmet_10 Y
date,,,,,,
1970-01-01 00:00:00.000,0.0,0.0,2278.008492,-2548.643513,0.0,0.0
1970-01-01 00:00:00.400,0.0,0.0,2280.056289,-2548.467334,0.0,0.0
1970-01-01 00:00:00.800,0.0,0.0,2281.127542,-2548.993780,0.0,0.0
1970-01-01 00:00:01.200,0.0,0.0,2283.390641,-2548.354744,0.0,0.0
1970-01-01 00:00:01.600,0.0,0.0,2285.273970,-2543.127341,0.0,0.0
1970-01-01 00:00:02.000,0.0,0.0,2285.513740,-2546.115441,0.0,0.0
1970-01-01 00:00:02.400,0.0,0.0,2285.557964,-2545.233203,0.0,0.0
1970-01-01 00:00:02.800,0.0,0.0,2284.819126,-2545.352558,0.0,0.0
1970-01-01 00:00:03.200,0.0,0.0,2286.082965,-2541.555965,0.0,0.0
1970-01-01 00:00:03.600,0.0,0.0,2287.081712,-2535.950361,0.0,0.0
1970-01-01 00:00:04.000,0.0,0.0,2288.032246,-2533.061937,0.0,0.0
1970-01-01 00:00:04.400,0.0,0.0,2288.859110,-2532.600489,0.0,0.0
1970-01-01 00:00:04.800,0.0,0.0,2290.530125,-2530.703432,0.0,0.0
1970-01-01 00:00:05.200,0.0,0.0,2294.102283,-2527.908909,0.0,0.0
1970-01-01 00:00:05.600,0.0,0.0,2297.458688,-2525.401937,0.0,0.0
1970-01-01 00:00:06.000,0.0,0.0,2297.337728,-2529.010878,0.0,0.0
1970-01-01 00:00:06.400,0.0,0.0,2297.651496,-2534.562743,0.0,0.0
1970-01-01 00:00:06.800,0.0,0.0,2297.710632,-2536.489334,0.0,0.0
1970-01-01 00:00:07.200,0.0,0.0,2296.829802,-2537.005824,0.0,0.0
1970-01-01 00:00:07.600,0.0,0.0,2298.594922,-2536.069020,0.0,0.0
1970-01-01 00:00:08.000,0.0,0.0,2298.530429,-2535.700044,0.0,0.0
1970-01-01 00:00:08.400,0.0,0.0,2296.598719,-2533.413200,0.0,0.0
1970-01-01 00:00:08.800,0.0,0.0,2294.379205,-2530.584911,0.0,0.0
1970-01-01 00:00:09.200,0.0,0.0,2289.541111,-2530.995486,0.0,0.0
1970-01-01 00:00:09.600,0.0,0.0,2287.461428,-2533.644180,0.0,0.0
1970-01-01 00:00:10.000,0.0,0.0,2290.166762,-2533.470415,0.0,0.0
1970-01-01 00:00:10.400,0.0,0.0,2293.341119,-2536.561355,0.0,0.0
1970-01-01 00:00:10.800,0.0,0.0,2293.865034,-2541.056507,0.0,0.0
1970-01-01 00:00:11.200,0.0,0.0,2293.502942,-2542.214920,0.0,0.0
1970-01-01 00:00:11.600,0.0,0.0,2298.382437,-2544.223584,0.0,0.0
1970-01-01 00:00:12.000,0.0,0.0,2304.421735,-2545.186796,0.0,0.0
1970-01-01 00:00:12.400,0.0,0.0,2304.805883,-2537.588066,0.0,0.0
1970-01-01 00:00:12.800,0.0,0.0,2300.028501,-2539.292499,0.0,0.0
1970-01-01 00:00:13.200,0.0,0.0,2295.162495,-2533.925131,0.0,0.0
1970-01-01 00:00:13.600,0.0,0.0,2289.283912,-2531.537516,0.0,0.0
1970-01-01 00:00:14.000,0.0,0.0,2281.132744,-2533.295226,0.0,0.0
1970-01-01 00:00:14.400,0.0,0.0,2273.139167,-2538.639794,0.0,0.0
1970-01-01 00:00:14.800,0.0,0.0,2267.534356,-2544.042313,0.0,0.0
1970-01-01 00:00:15.200,0.0,0.0,2207.661869,-2481.233138,0.0,0.0
1970-01-01 00:00:15.600,0.0,0.0,2261.029241,-2540.347419,0.0,0.0
1970-01-01 00:00:16.000,0.0,0.0,2259.979609,-2539.991864,0.0,0.0
1970-01-01 00:00:16.400,0.0,0.0,2263.650771,-2540.264163,0.0,0.0
1970-01-01 00:00:16.800,0.0,0.0,2263.477902,-2540.134483,0.0,0.0
1970-01-01 00:00:17.200,0.0,0.0,2264.710738,-2542.532340,0.0,0.0
1970-01-01 00:00:17.600,0.0,0.0,2265.835275,-2540.431219,0.0,0.0
1970-01-01 00:00:18.000,0.0,0.0,2268.210138,-2541.510183,0.0,0.0
1970-01-01 00:00:18.400,0.0,0.0,2268.160502,-2540.393135,0.0,0.0
1970-01-01 00:00:18.800,0.0,0.0,2267.364324,-2544.562249,0.0,0.0
1970-01-01 00:00:19.200,0.0,0.0,2269.447935,-2543.809885,0.0,0.0
1970-01-01 00:00:19.600,0.0,0.0,2271.639308,-2543.341507,0.0,0.0
1970-01-01 00:00:20.000,0.0,0.0,2271.770843,-2548.265019,0.0,0.0
1970-01-01 00:00:20.400,0.0,0.0,2271.847064,-2551.709622,0.0,0.0
1970-01-01 00:00:20.800,0.0,0.0,2274.260015,-2552.366673,0.0,0.0
1970-01-01 00:00:21.200,0.0,0.0,2273.805973,-2552.396829,0.0,0.0
1970-01-01 00:00:21.600,0.0,0.0,2273.219330,-2551.409868,0.0,0.0
1970-01-01 00:00:22.000,0.0,0.0,2272.364446,-2549.653667,0.0,0.0
1970-01-01 00:00:22.400,0.0,0.0,2270.151918,-2550.107405,0.0,0.0
1970-01-01 00:00:22.800,0.0,0.0,2269.625378,-2550.931413,0.0,0.0
1970-01-01 00:00:23.200,0.0,0.0,2270.396850,-2551.354352,0.0,0.0
1970-01-01 00:00:23.600,0.0,0.0,2272.336153,-2548.217260,0.0,0.0